### ISSUE TITLE
file /etc/systemd/system/gosearch.service is marked executable

### ISSUE THREAD

**Issue by simonbcn** [ozeidan/gosearch#1]
```
Arch Linux
gosearch git version
```
journal shows this error: `systemd[1]: Configuration file /etc/systemd/system/gosearch.service is marked executable. Please remove executable permission bits. Proceeding anyway.`

**Comment by ozeidan** [comment]
Hi, thanks for creating the issue.

Yes, the service file should probably not be executable. Weirdly enough I don't get this error.

Could you run:
`sudo chmod -v 0644 gosearch.service
make install`
and see if the error goes away?

**Comment by simonbcn** [comment]
Yes, removing executable permission to `gosearch.service` solves the warning.
