### ISSUE TITLE
Search locks up

### ISSUE THREAD

**Issue by vredesbyyrd** [ozeidan/gosearch#10]
**env info:**

linux-ck 5.1.6-1 (distro arch)
gosearch: commit f8254a3
Budgie 10.5

Hi, thank you for sharing this amazing search tool.

On the latest commit, gosearch is still often locking up when making search queries. I assume its related to issue #4 ,  although I do not know how to debug it. Restarting the service will temporarily fix the issue. Here is a screenshot of the log during the crash.  

![Screenshot from 2019-06-03 20-01-13](https://user-images.githubusercontent.com/22080838/58844386-9bb4fc00-863c-11e9-9a6b-58ecc387ec2f.png)

Since the error says `...too many open files` I thought fanotify may just be watching too many directories/files, I was able to cut down my index size quite a bit by blacklisting unnecessary directories and files that are constantly changing. But the problem still persists. 

Before: 
`
indexed 1063683 files and 105518 directories in 12.901094 seconds`

After 

`indexed 527819 files and 40704 directories in 6.845391 seconds`

If there is any information you want that could be helpful please let me know.

**Comment by simonbcn** [comment]
Same problem with last version (`gosearch-git r49.f8254a3`).

**Comment by ozeidan** [comment]
Hi guys, thanks for reporting. I'm unable to reproduce the lockup this time. Is it something particular that you do when it locks up?

I did fix a file descriptor leak on the master branch, the 'too many open files' error might be coming from that. Could you please test again?

**Comment by vredesbyyrd** [comment]
Hi, I just rebuilt with commit 7d124c74a7b4375f38b62a96a5aa07b0ae706541 and unfortunately I can still reproduce the issue. 
 
There does not seem to be much rhyme or reason in what triggers it. The specific search query appears to be irrelevant. I can search `Johann\ Johannsson` with no issue, but a few minutes later it will lock up performing the same query.  

The only pattern I see is it only happens when I have not made a search query for at least a few minutes, 3-5 minutes is an rough estimate. If I just continue to do consecutive random queries it does not seem to occur.

On commit 7d124c74a7b4375f38b62a96a5aa07b0ae706541 the error is same as prior commits. ( I stopped and restarted the service after rebuilding) When making a query that results in a lockup, the first error is: 

`request.go:74: accept error: accept unix /run/gosearch.sock: accept4: too many open files` 

followed by: 

`Suppressed 734585 messages from gosearch.service` (the amount of suppressed messages seems to mirror the size of the index, i think.) 

Which brings me to the other messages in the log, which is printed anytime `gosearch.service` is running. 

`fanotify.go:144: received event, path: '/some/filepath' flags: fanMovedFrom, fanMovedTo` 

What confuses me is there are thousands of these messages reporting events on paths I have filtered in the config, e.g 

`fanotify.go:144: received event, path: /home/clu/.mozilla/firefox/iujq4eo8.default/sessionstore-backups flags: fanMovedFrom, fanMovedTo` 

I have `/home/clu/.mozilla` blacklisted  with a prefix filter, which is correctly NOT being indexed. If a path is filtered, should fanotify still watch and report events on said path? 

I was going to file a different bug report for that, but figured i'd mention it here instead since the cause of the 'search lockup' is still unknown. 

Thanks for your time.

**Comment by ozeidan** [comment]
Hi, you're right, the commit doesn't really fix the issue. So I believe the problem is that the program opens a lot of files at some point and doesn't close them properly. If you run `sudo lsof -Ki | grep gosearch`, you should be able to see an excessive amount of entries, is that correct? So when the limit of open files is reached, the server locks up. Maybe I have not encountered this error, because the limit is higher on my system. I'll try to look at the issue a little bit closer.

For the second thing you mentioned: fanotify is currently being called on the root of the filesystem, independent of the filter settings. Though the filtered files are neither indexed at startup nor when we receive an event. It might be interesting to call fanotify multiple times on subtress of the filesystem, though I'm not sure if the overhead of the current method is large enough to justify the additional complexity. 

It might be better to only log the unfiltered events though.

**Comment by vredesbyyrd** [comment]
@simonbcn 

Are you using a stock kernel? e.g not `linux-ck, linux-zen` etc?  I am using linux-ck on arch linux. I am just wondering if there are any similarities with are environments. Correlation does not imply causation but it could help narrow things down. Thanks.

**Comment by ozeidan** [comment]
I realized my mistake in the previous commit and implemented the fix for the file descriptor leak more cleanly. Could you please test again if the lock happens? Please also check if open files are accumulating over time with `sudo lsof -Ki | grep gosearch`.

**Comment by vredesbyyrd** [comment]
> If you run sudo lsof -Ki | grep gosearch, you should be able to see an excessive amount of entries, is that correct? 

That is correct. There is an excessive amount of entries, mostly all from firefox cache directories. [log](https://pastebin.com/) 

Thank you for clarifying that second part. 

> It might be better to only log the unfiltered events though.

I could be onboard with that. If I knew go I would help out on some of this stuff. 

EDIT: just saw your new message, will test latest commits and report back.

**Comment by vredesbyyrd** [comment]
At risk of speaking too soon, but I am fairly confident the lock up is fixed. Have not been able to reproduce the issue and open files are not accumulating.  The output of `sudo lsof -Ki | grep gosearch` is staying the same. Much better!   

```
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
gosearchS 11652             root  cwd       DIR               8,23         4096          2 /
gosearchS 11652             root  rtd       DIR               8,23         4096          2 /
gosearchS 11652             root  txt       REG               8,23      3945680     140139 /usr/bin/gosearchServer
gosearchS 11652             root  mem       REG               8,23      2141720     134198 /usr/lib/libc-2.29.so
gosearchS 11652             root  mem       REG               8,23       155600     134252 /usr/lib/libpthread-2.29.so
gosearchS 11652             root  mem       REG               8,23       197808     134185 /usr/lib/ld-2.29.so
gosearchS 11652             root    0r      CHR                1,3          0t0      11734 /dev/null
gosearchS 11652             root    1u     unix 0x00000000ad019f2b          0t0   31283997 type=STREAM
gosearchS 11652             root    2u     unix 0x00000000ad019f2b          0t0   31283997 type=STREAM
gosearchS 11652             root    4u  a_inode               0,13            0       2064 [eventpoll]
gosearchS 11652             root    5u     unix 0x00000000ed845e10          0t0   31283998 /run/gosearch.sock type=STREAM
gosearchS 11652             root    6u  a_inode               0,13            0       2064 [fanotify]
```
Thank you for resolving this so promptly. I will leave this open for now and close tonight if the issue does not resurface. 

On a different note, would it be possible to merge these changes / current master into the `path_fuzzy_finding` branch? I wanted to do some testing with that branch if possible but was having trouble merging the branches because of conflicts. When time abides, I am writing a simple rofi gui for gosearch and currently working on how the output is formatted in rofi. 

Thanks again for your time.

**Comment by ozeidan** [comment]
@vredesbyyrd thank you as well for testing!

I merge the master branch into path_fuzzy_finding. I am curious as to know what you think about the path matching feature. I'm not sure if it should be merged into master, as it adds to the memory footprint and initial indexing time of gosearch. So please let me know how it performs on your system and feel free to open issues if you encounter any more problems. :slightly_smiling_face:

**Comment by vredesbyyrd** [comment]
Sounds good and thank you for merging the latest changes into path_fuzzy_finding. I forked it and will do some testing tonight with your thoughts regarding the branch in mind, and I will definitely report back :) 

Cheers.

**Comment by simonbcn** [comment]
I have tested it these days and it works well for me with the latest changes.
