### ISSUE TITLE
Add ConditionKernelVersion to systemd service 

### ISSUE THREAD

**Issue by simonbcn** [ozeidan/gosearch#13]
To ensure that the gosearch server only boots if the kernel is greater than or equal to version 5.1. it would be advisable to add `ConditionKernelVersion=>=5.1` to the `gosearch.service` file:
```
[Unit]
Description=gosearch file indexing server
ConditionKernelVersion=>=5.1

[Service]
...
```

**Comment by ozeidan** [comment]
Hey, good idea. I added the condition to the service file, it seems to work fine. Maybe the error message could be a little bit nicer, currently it only says "Condition check resulted in gosearch file indexing server being skipped.". But I think for now that's ok. Thanks for the input

**Comment by simonbcn** [comment]
Yes, the message isn't very descriptive. But the `systemctl status gosearch.service` is clearer:
```
● gosearch.service - gosearch file indexing server
   Loaded: loaded (/etc/systemd/system/gosearch.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2019-06-26 10:18:51 CEST; 14s ago
Condition: start condition failed at Wed 2019-06-26 10:18:51 CEST; 14s ago
           └─ ConditionKernelVersion=>=5.2 was not met
  Process: 14118 ExecStart=/usr/bin/gosearchServer (code=killed, signal=TERM)
 Main PID: 14118 (code=killed, signal=TERM)

jun 26 10:18:51 arch-juan systemd[1]: gosearch.service: Main process exited, code=killed, status=15/TERM
```
The `5.2` is for testing. :wink:
