### ISSUE TITLE
Broken pipe when the client closes the connection early

### ISSUE THREAD

**Issue by ozeidan** [ozeidan/gosearch#4]
There is an issue sometimes with the server pipe breaking. In this case, the search queries will return no result and never terminate. It can be reproduced by running a large query (i.e. fuzzy searching with the query 'e') and then terminating the client program with Ctrl + C.

For now you can restart the server program to mitigate this problem. (`sudo systemctl restart gosearch.service`).

I'm not sure how to handle this issue yet. The problem starts when the server wants to write a result to the socket connection when it was already closed by the client. Just rebuilding the whole socket when this happens seems counter intuitive.

**Comment by simonbcn** [comment]
I have this problem too but sorry I can't help you.

**Comment by ozeidan** [comment]
Hi @simonbcn, the bug should be fixed on the master branch. Could you please confirm that?

**Comment by simonbcn** [comment]
The problem still persist. I continue with this in #10
