### ISSUE TITLE
Blacklisting directories 

### ISSUE THREAD

**Issue by vredesbyyrd** [ozeidan/gosearch#8]
Thank you for creating and sharing this tool. The changes in kernel 5.1 make for some exciting possibilities regarding search tools. 

I am trying to blacklist some directories so they are not indexed, but cant seem to properly filter them out.  Relevant part of the error log:  

`failed to initialize configuration invalid character '/' looking for beginning of value`

I feel stupid asking, but how should the config look if I wanted to blacklist the following paths: 

`.mozzila, .cache, /foo/bar`

Thank you for your time.

**Comment by ozeidan** [comment]
Hi, so the default config should look like
```
{
    "prefix_filters": [],
    "substring_filters": [],
    "regex_filters": [],
    "ignore_hidden_files": false,
    "print_logs": true,
    "file_logs": false,
    "home_only": false
}
```
The `filters` objects are arrays of strings, so you can change them to something like `["/sys", "/proc/]`. For the directories that you have, I would suggest changing `substring_filters` to  ["/.mozzila/", "/.cache/"] and `prefix_filters` to `["/foo/bar"]. So in general, `prefix_filters` are absolute paths and `substring_filters` are any path string that contains X.

**Comment by vredesbyyrd** [comment]
Thank you for the clear description :) The filtered directories are no longer being indexed, as requested. I was missing the quotes, uhg. 

Now I will get on with some real-world testing / usage. Everything looks great so far. 

cheers.
